apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
    app: python-api
    app.kubernetes.io/managed-by: Helm

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.rollout.minReadySeconds }}

  strategy:
    type: {{ .Values.rollout.strategy.type }}
    {{- if eq .Values.rollout.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.rollout.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollout.strategy.rollingUpdate.maxSurge }}
    {{- end }}

  selector:
    matchLabels:
      app: python-api

  template:
    metadata:
      labels:
        app: python-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.service.targetPort }}"

    spec:
      containers:
        - name: python-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: redis-cm

            - secretRef:
                name: redis-secret
