replicaCount: 1

image:
  repository: python-api
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"

  host: redis
  port: "6379"

  password: redis-123

  persistence:
    enabled: true
    size: 1Gi
    storageClassName: standard

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /api(/|$)(.*)

rollout:
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
