replicaCount: 1

image:
  tag: ci-7-b14a41a
  pullPolicy: Always

  repository: 617791431348.dkr.ecr.us-east-1.amazonaws.com/redis-fastapi
service:
  type: ClusterIP
  port: 80
  targetPort: 8000

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"

  host: redis
  port: "6379"

  persistence:
    enabled: false

ingress:
  enabled: false

rollout:
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
